# Use the official Python image from the Docker Hub
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY requirements.txt .

# Install any dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . .

# Define environment variable
ENV DJANGO_SETTINGS_MODULE=MosqueAppchild.settings
ENV PYTHONPATH=/app/MosqueApp

# Run the Celery worker
CMD ["celery", "-A", "MosqueAppchild", "worker", "--loglevel=info"]
