# Generated by Django 5.0.6 on 2024-05-20 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosque',
            fields=[
                ('mosque_id', models.AutoField(primary_key=True, serialize=False)),
                ('mosquename', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('profile_pic', models.CharField(blank=True, max_length=255)),
                ('prayer_times', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('media_type', models.CharField(blank=True, max_length=20)),
                ('media_url', models.CharField(blank=True, max_length=255)),
                ('events', models.CharField(blank=True, max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mosque')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('follow_id', models.AutoField(primary_key=True, serialize=False)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mosque')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
            options={
                'unique_together': {('user', 'mosque')},
            },
        ),
    ]
