# Generated by Django 5.0.6 on 2024-06-09 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='address',
            new_name='location',
        ),
        migrations.AddField(
            model_name='mosque',
            name='grid_cell_lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mosque',
            name='grid_cell_lon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mosque',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='mosque',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
