# Generated by Django 5.0.6 on 2024-06-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_address_customuser_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='grid_cell_lat',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='grid_cell_lon',
            field=models.FloatField(default=0.2),
        ),
    ]
