# Generated by Django 5.0.6 on 2024-06-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_mosque_grid_cell_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='location',
        ),
        migrations.AddField(
            model_name='customuser',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='grid_cell_lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mosque',
            name='grid_cell_lon',
            field=models.IntegerField(default=0),
        ),
    ]
