# Generated by Django 5.0.6 on 2024-06-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_customuser_location_customuser_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
