# Generated by Django 5.0.6 on 2024-06-12 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_customuser_lat_alter_customuser_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
