# Generated by Django 5.0.6 on 2024-06-12 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_customuser_lat_alter_customuser_lon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='lon',
            new_name='longitude',
        ),
    ]
