# Generated by Django 5.0.6 on 2024-06-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_mosque_nonprofitform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mosque',
            name='grid_cell_lat',
        ),
        migrations.RemoveField(
            model_name='mosque',
            name='grid_cell_lon',
        ),
        migrations.AddField(
            model_name='customuser',
            name='grid_cell_lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grid_cell_lon',
            field=models.IntegerField(default=0),
        ),
    ]
