# Generated by Django 5.0.6 on 2024-07-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mosque_grid_cell_lat_mosque_grid_cell_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='media_url',
        ),
        migrations.AddField(
            model_name='post',
            name='media_file',
            field=models.FileField(default='placeholder_media', upload_to='media/'),
        ),
    ]
