# Generated by Django 5.0.6 on 2024-08-03 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_post_media_url_post_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='address',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.mosque'),
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=255)),
                ('event_date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('event_description', models.TextField()),
                ('rsvp', models.BooleanField(default=False)),
                ('mosque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mosque')),
            ],
        ),
    ]
