# Generated by Django 5.0.6 on 2024-08-04 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_mosque_address_alter_post_mosque_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='mosque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='myapp.mosque'),
        ),
    ]
