# Generated by Django 5.0.6 on 2024-09-01 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_events_mosque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
