# Generated by Django 5.0.6 on 2024-09-05 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_post_media_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='events',
            new_name='event_details',
        ),
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='media_file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='posttype',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('media', 'Media Post'), ('event', 'Event')], max_length=20),
        ),
    ]
