# Generated by Django 5.0.6 on 2025-02-04 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_post_nonprofitform_mosque_nonprofitform'),
    ]

    operations = [
        migrations.AddField(
            model_name='mosque',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
