# Generated by Django 5.0.6 on 2025-04-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_mosque_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='profile_pic',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
