# Generated by Django 5.0.6 on 2025-04-05 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_alter_mosque_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
