# Generated by Django 5.0.6 on 2025-04-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_mosque_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mosque',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='mosque_profile_pics/'),
        ),
    ]
